app:
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
  pdb:
    minAvailable: 1
horizon:
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
cron:
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
queue:
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
reverb:
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
redis:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 0.05
    limits:
      memory: 2Gi
      cpu: 2
ingress:
  host: ef-streaming.eurofurence.org
  annotations: {}

image:
  repository: eurofurence/XXXXXXXX
  pullPolicy: IfNotPresent
  tag: edge
