apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel.fullname" . }}-caddyfile
  labels:
    app: {{ template "laravel.name" . }}-caddyfile
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  laravel.conf: |-
    :8080 {
        root * /app/public
        file_server
        header {
            header /build/* Cache-Control max-age=31536000
            header /vendor/* Cache-Control max-age=31536000
        }
    }