{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "laravel.fullname" . }}-env-secrets
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug }}
        envSlug: {{ .Values.infisical.envSlug }}
        secretsPath: {{ .Values.infisical.secretsPath }}
        recursive: {{ .Values.infisical.recursive }}
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsRef.secretName }}
        secretNamespace: {{ .Values.infisical.credentialsRef.secretNamespace }}
  managedSecretReference:
    secretName: {{ include "laravel.managedSecretReference" . }}
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: {{ .Values.infisical.managedSecretReference.creationPolicy }}
{{- end }}