apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-migrations
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "laravel.fullname" . }}-env
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          args:
            - php
            - artisan
            - migrate
            - --force
            - --seed
      restartPolicy: OnFailure